name: findany_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_database: ^10.4.11
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  flutter_easyloading: ^3.0.5
  flutter_styled_toast: ^2.2.1
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  open_file: ^3.3.2
  gsheets: ^0.5.0
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.2.5
  change_app_package_name: ^1.1.0
  dio: ^5.4.2+1
  flutter_cache_manager: ^3.3.1
  provider: ^6.1.2
  in_app_update: ^4.2.2
  firebase_crashlytics: ^3.5.0
  firebase_analytics: ^10.10.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.1
  image_cropper: ^5.0.1
  dash_chat_2: ^0.0.20
  rxdart: ^0.27.7
  async: ^2.11.0
  firebase_messaging: ^14.8.1
  flutter_local_notifications: ^17.0.1
  logger: ^2.2.0
  http: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google-signin-button.png
    - assets/images/xerox.png
    - assets/images/defaultimage.png
    - assets/images/groupchat.jpg

