name: findany_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  firebase_database: ^10.5.5
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  flutter_easyloading: ^3.0.5
  file_picker: ^8.0.3
  open_file: ^3.3.2
  path_provider: ^2.1.2
  gsheets: ^0.5.0
  flutter_secure_storage: ^9.2.1
  url_launcher: ^6.2.6
  dio: ^5.4.3+1
  flutter_cache_manager: ^3.3.1
  in_app_update: ^4.2.2
  firebase_crashlytics: ^3.5.5
  firebase_analytics: ^10.10.5
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  dash_chat_2: ^0.0.20
  rxdart: ^0.27.7
  async: ^2.11.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  http: ^1.2.1
  razorpay_flutter: ^1.3.6
  path: ^1.9.0
  google_maps_flutter: ^2.6.1
  intl: ^0.18.1
  fluttertoast: ^8.2.5
  flutter_pdfview: ^1.3.2
  flutter_signin_button: ^2.0.0
  shimmer: ^3.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/xerox.png
    - assets/images/defaultimage.png
    - assets/images/groupchat.png
    - assets/images/logo.png
    - assets/images/materials.png
    - assets/images/navigation.png
    - assets/images/marker.png
    - assets/images/transperentlogo.png
    - assets/images/universitynews.jpeg
    - assets/images/busbooking.png
    - assets/images/earnmoney.png

